debug = False

BG_COLOR = (192, 192, 192)

# Dimentions
BOX_SIZE = 32
BORDER = 22
TOP_AREA = BOX_SIZE * 2

MENU_COLS = 10
MENU_ROWS = 8
MENU_WIDTH = MENU_COLS * BOX_SIZE + BORDER * 2
MENU_HEIGHT = MENU_ROWS * BOX_SIZE + TOP_AREA + BORDER * 3

FACE_W = 52

# Locations
GRID_LOC_X = BORDER
GRID_LOC_Y = TOP_AREA + BORDER * 2
COUNTER_LOC = BORDER + 6
FACE_LOC_Y = (BORDER + TOP_AREA / 2) - FACE_W / 2
